# Generated by Django 3.2.4 on 2021-06-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='exclude',
            new_name='excerpt',
        ),
    ]
